### ISSUE TITLE
Using keboola instead of own csv implementation

### ISSUE THREAD

**Issue by Sgoettschkes** [plumphp/plum-csv#1]
Keboola is a very stable csv reader/writer and to me, it doesn't make sense to re-implement csv reading/writing within this package.

If it's ok with you, I'd add a CsvReader which depends on keboola as a first step. In a second step, replacing the current writer with one that depends on keboola would make sense.

**Comment by florianeckerstorfer** [comment]
I don't have any experience with Keboola, but what do you think of `League\Csv` (see http://csv.thephpleague.com). It has some nice features (such as adding BOM for Microsoft Excel).

**Comment by Sgoettschkes** [comment]
Didn't know about `League\Csv`. Looks interesting though. Give me some time to play around with it and I'll give you feedback on what I think is the best approach.

**Comment by Sgoettschkes** [comment]
Gave it a try, looks pretty good. Take a look at my Reader/Writer: https://github.com/agileaddicts/cllctr/tree/master/src/Cllctr/BackendBundle/DataProcessing

Pretty clean as the Csv reader and writer handle almost everything. The classes are really just a wrapper around. What do you think?

**Comment by florianeckerstorfer** [comment]
I think it looks great. However, I think it should be also possible to set the file using the constructor.

**Comment by Sgoettschkes** [comment]
@florianeckerstorfer I see the CsvWriter is under development. Do you want me to switch it over to the `League/Csv/CsvWriter` if you are done or do you want to keep it the current way?

**Comment by florianeckerstorfer** [comment]
@Sgoettschkes I am currently using `CsvWriter` in a project and I needed that `autoDetectHeader()` option. If you like you can switch to using League any time. However, they should have the same features. (which should be easy, because there is not a lot).
