### ISSUE TITLE
Use header column in CsvReader

### ISSUE THREAD

**Issue by Sgoettschkes** [plumphp/plum-csv#4]
I am facing the problem where I'd like to have the `CsvReader` output as an associated array where each row from the csv is an array of keys and values with the keys being the cells from the first row of the csv.

So given my csv is like

```
C1,C2,C3
1,2,3
4,5,6
```

I'd get back an array with

```
[
    ['C1' => '1', 'C2' => '2', 'C3 => '3'],
    ['C1' => '4', 'C2' => '5', 'C3 => '6']
]
```

My idea would be to have a `HeaderDetectionConverter` which takes each array and returns an associated array. In case it's the first row, it saves the array as header definition.

I need your input on some things:
1. Should this converter be part of the `plum-csv` package?
2. How would I name it. I am not finding the right name
3. Is it possible for a converter to also remove elements from the chain? The first row should not be part of the result, so I'd need to store it away and then remove it.
   1. If not, how would you approach this? Add a filter as well? Maybe we can improve the plum workflow itself to support such things?

**Comment by florianeckerstorfer** [comment]
`ddeboer/data-import` uses a method on the `CsvReader` called `setHeaderRow()` (or something similar to that). When the value is set the row with the given number is used as keys for the element.

**Comment by Sgoettschkes** [comment]
I checked it but didn't get anywhere. I'll implement a solution I got in my head and do a PR to see if this fits your needs.

**Comment by Sgoettschkes** [comment]
The difference between the [CsvReader from data-import](https://github.com/ddeboer/data-import/blob/master/src/Ddeboer/DataImport/Reader/CsvReader.php) and your CsvReader is that yours is exposing the iterator. The Reader could internally read all rows and transform them, then exposing an iterator to this internal object, but this won't work with big csv files. I'll implement a Converter for now and we can discuss using it as an example.
